<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Configuration\**" />
    <Compile Remove="Features\**" />
    <Compile Remove="Security\**" />
    <EmbeddedResource Remove="Configuration\**" />
    <EmbeddedResource Remove="Features\**" />
    <EmbeddedResource Remove="Security\**" />
    <None Remove="Configuration\**" />
    <None Remove="Features\**" />
    <None Remove="Security\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookStore.Domain\BookStore.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Registrations\VerifyRegistration\" />
    <Folder Include="Users\Commands\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
